# Generated by Django 4.0.3 on 2022-04-05 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like_coount',
            new_name='likecount',
        ),
    ]
